version: '3'
services:
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: robot
      POSTGRES_DB: robot
      POSTGRES_PASSWORD: robot
    networks:
      - robot
    hostname: 127.0.0.1
    ports:
      - "5432:5432"
  db-master:
    image: glab16/db_master:latest
    container_name: db_master
    restart: always
    environment:
      PORT: 3002
      DATABASE: robot
      DB_USER: robot
      DB_PASSWORD: robot
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DIALECT: postgres
      IS_DEV: true
    networks:
      - robot
    hostname: 127.0.0.1
    ports:
      - "3002:3002"
networks:
  robot:
    external: true
