version: '3'
services:
  postgres-11:
    image: postgres:13.4-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: robot
      POSTGRES_DB: robot
      POSTGRES_PASSWORD: robot
    ports:
      - "5432:5432"
