version: '3'
services:
  postgres-11:
    image: postgres:13.4-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: robot
      POSTGRES_DB: robot
      POSTGRES_PASSWORD: robot
    networks:
      - docker-robot-network
    ports:
      - "5432:5432"
networks:
  my-network:
    external: true
