version: '3'
services:
  db-master:
    image: glab16/db_master:latest
    container_name: db_master
    restart: always
    environment:
      PORT: 3002
      DATABASE: robot
      DB_USER: robot
      DB_PASSWORD: robot
      DB_HOST: localhost
      DB_PORT: 5432
      DIALECT: postgres
    ports:
      - "3002:3002"
