version: '3'
services:
  db-master:
    image: glab16/db_master:latest
    container_name: db_master
    restart: always
    environment:
      PORT: 3002
      DATABASE: robot
      DB_USER: robot
      DB_PASSWORD: robot
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DIALECT: postgres
      IS_DEV: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - docker-robot-network
    ports:
      - "3002:3002"
networks:
  my-network:
    external: true
